import type { Metadata } from "next";
import { Overpass_Mono } from "next/font/google";
import "./globals.css";

const overpass_mono = Overpass_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={overpass_mono.className}>{children}</body>
    </html>
  );
}
